// CD:

// pipeline {
//     agent any
    
//     environment {
//         EC2_HOST = '13.235.243.213'
//         EC2_USER = 'ubuntu'
//         NEXUS_URL = 'http://nexus:8081'
//         NEXUS_REPOSITORY = 'maven-releases'
//         ARTIFACT_GROUP = 'com.example.laundry'
//         ARTIFACT_ID = 'LaundryApp'
//         ARTIFACT_VERSION = '1.1.1'
//         JAR_NAME = 'LaundryApp-1.1.1.jar'
//         SSH_HOME='/home/ubuntu'
//     }
    
//     stages {
//         stage('Test SSH Connection') {
//             steps {
//                 script {
//                     sshagent(['mells-server']) {
//                         sh """
//                         ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${EC2_USER}@${EC2_HOST} '
//                             echo "SSH connection successful!"
//                             whoami
//                             hostname
//                             uptime
//                         '
//                         """
//                     }
//                 }
//             }
//         }
//         stage('Installing Java & checking version') {
//             steps {
//                 script {
//                     sshagent(['mells-server']) {
//                         sh """
//                         ssh ${EC2_USER}@${EC2_HOST} '
//                             echo "SSH connection successful!"
//                             dpkg -s openjdk-17-jdk &> /dev/null || sudo apt update && sudo apt install -y openjdk-17-jdk
//                             java -version
//                         '
//                         """
//                     }
//                 }
//             }
//         }
//         stage ('downloading jar') {
//             steps {
//                 sh 'curl -u admin:admin -O ${NEXUS_URL}/repository/maven-releases/com/example/laundry/LaundryApp/1.1.1/${JAR_NAME}'
//                 sh 'ls -alth'
//             }
//         }
//         stage('Sending files over scp') {
//             steps {
//                 script {
//                     sshagent(['mells-server']) {
//                         sh 'scp ./${JAR_NAME} ${EC2_USER}@${EC2_HOST}:${SSH_HOME}'
//                     }
//                 }
//             }
//         }
//         stage('Running Java jar') {
//             steps {
//                 script {
//                     sshagent(['mells-server']) {
//                         sh """
//                         ssh ${EC2_USER}@${EC2_HOST} '
//                             echo "SSH connection successful!"
//                             pwd
//                             java -jar ${JAR_NAME}
//                         '
//                         """
//                     }
//                 }
//             }
//         }
//     }
// }


pipeline {
    agent any
    
    environment {
        REMOTE_HOST = '13.126.106.58'
        REMOTE_USER = 'ubuntu'
        REMOTE_PASSWORD = credentials('cd-ec2-ssh')
        
        // Nexus artifact details
        NEXUS_URL = 'http://nexus:8081'
        ARTIFACT_PATH = 'maven-releases/com/example/laundry/LaundryApp/1.1.1/LaundryApp-1.1.1.jar'
    }

    stages {
        stage('Download Artifact') {
            steps {
                // Download artifact from Nexus to workspace
                sh """
                    curl -o LaundryApp-1.1.1.jar "${NEXUS_URL}/repository/${ARTIFACT_PATH}"
                """
            }
        }
        
        stage('SSH to Remote Server') {
            steps {
                sshagent(credentials: ['cd-ec2-ssh']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} '
                            echo "Successfully connected to remote server"
                            pwd
                            ls -la
                            sudo apt update -y
                            sudo apt install openjdk-17-jre -y
                            sudo mkdir -p /apps/
                            sudo chown ubuntu:ubuntu /apps
                            cd /apps
                            nohup java -jar LaundryApp-1.1.1.jar >> app.log 2>&1 &
                            echo "Application started in background"
'                        '
                    """
                }
            }
        }
    }
}