pipeline {
    agent any
    
    environment {
        REMOTE_HOST = '13.126.106.58'
        REMOTE_USER = 'ubuntu'
        REMOTE_PASSWORD = credentials('cd-ec2-ssh')
        
        // Nexus artifact details
        NEXUS_URL = 'http://nexus:8081'
        ARTIFACT_PATH = 'maven-releases/com/example/laundry/LaundryApp/1.1.1/LaundryApp-1.1.1.jar'
    }

    stages {
        stage('Download Artifact') {
            steps {
                // Download artifact from Nexus to workspace
                sh """
                    curl -o LaundryApp-1.1.1.jar "${NEXUS_URL}/repository/${ARTIFACT_PATH}"
                """
            }
        }
        
        stage('Install Basic') {
            steps {
                sshagent(credentials: ['install-basic']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} '
                            echo "Installing basic requirements"
                            sudo apt update -y
                            sudo apt install openjdk-17-jre -y
                            sudo mkdir -p /apps/
                            sudo chown ubuntu:ubuntu /apps
                        '
                    """
                }
            }
        }
        
        stage('Deploy Application') {
            steps {
                sshagent(credentials: ['Depoying-app']) {
                    sh """
                        scp -o StrictHostKeyChecking=no LaundryApp-1.1.1.jar ${REMOTE_USER}@${REMOTE_HOST}:/apps/
                        ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} '
                            cd /apps
                            nohup java -jar LaundryApp-1.1.1.jar >> app.log 2>&1 &
                            echo "Application started in background"
                        '
                    """
                }
            }
        }
    }
}