pipeline{
    agent any
    tools {
        maven 'mvn'
    }
    environment {
        NEXUS_URL = 'http://nexus:8081'
        NEXUS_REPOSITORY = 'maven-releases'
        ARTIFACT_GROUP = 'com.example.laundry'
        ARTIFACT_ID = 'LaundryApp'
        ARTIFACT_VERSION = '1.1.1'
        ARTIFACT_FILE = 'maven-app/target/LaundryApp-1.0-SNAPSHOT.jar'
        NEXUS_CREDENTIALS = 'nexus'  // Ensure this is set in Jenkins credentials
    }

    stages{
        stage('Stage1-clone-code'){
            steps{
                git branch: 'main', credentialsId: 'github-april-token', url: 'https://github.com/devopsdecode/april-2025.git'
            }
        }
        stage('BUILD and Package'){
        steps {
            dir ('maven-app'){
                    sh 'mvn package'
                }
            }
        }
        stage('Push to nexus'){
            steps {
                dir('maven-app') {
                    script {
                        withCredentials([usernamePassword(credentialsId: "${NEXUS_CREDENTIALS}", usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                            sh """
                            mvn deploy:deploy-file \
                                -Durl=${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/ \
                                -DrepositoryId=nexus \
                                -Dfile=target/LaundryApp-1.0-SNAPSHOT.jar \
                                -DgroupId=${ARTIFACT_GROUP} \
                                -DartifactId=${ARTIFACT_ID} \
                                -Dversion=${ARTIFACT_VERSION} \
                                -Dpackaging=jar \
                                --settings ./settings.xml
                            """
                        }
                    }
                }
            }
        }
        
    }
}
