pipeline{
    agent any
    tools {
        maven 'mvn'
    }
    stages{
        stage('Stage1-clone-code'){
            steps{
                git branch: 'main', credentialsId: 'github-april-token', url: 'https://github.com/devopsdecode/april-2025.git'
            }
        }
        stage('BUILD and Package'){
        steps {
            dir ('maven-app'){
                    sh 'mvn package'
                }
            }
        }
    }
}
